### ISSUE TITLE
getaddrinfo is failing with a local server in version 3.2

### ISSUE THREAD

**Issue by ColinRobbins** [aio-libs/aiodns#126]
The issue was originally reported in https://github.com/aio-libs/aiodns/issues/127, but traced to a upgrade from aiodns 3.1 to 3.2. 

Test code and logs are in the report on https://github.com/aio-libs/aiodns/issues/127.   
I can copy stuff over here if necessary.

**Comment by saghul** [comment]
Can you please copy the relevant context here?

Bonus points if it includes small steps to reproduce the problem.
